config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get '/about' => 'homes#about'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include ApplicationHelper
    def create
        #! request.env['omniauth.auth'][:uid]にデータが入っていないなら
        unless request.env['omniauth.auth'][:uid]
          flash[:message] = '連携に失敗しました'
          redirect_to root_url
        end
        #! Jsonの代入
        user_data = request.env['omniauth.auth']
        #! Userモデルのuidにuser_data[:uid]を代入
        user = User.find_by(uid: user_data[:uid])
        #! Userに値が入っているならログイン
        if user
          log_in user
          flash[:message] = 'ログインしました'
          redirect_to root_url
        #! Userに値が入っていないなら新規登録
        else
          new_user = User.new(
            uid: user_data[:uid],
            nickname: user_data[:info][:nickname],
            name: user_data[:info][:name],
            image: user_data[:info][:image],
            description: user_data[:info][:description]
          )
          #! 保存に成功したら
          if new_user.save
            log_in new_user
            flash[:message] = 'ユーザー登録成功'
          #! 保存に失敗したら
          else
            flash[:message] = '予期せぬエラーが発生しました'
          end
          redirect_to root_url
        end
      end

      def destroy
        log_out if logged_in?
        flash[:message] = 'ログアウトしました'
        redirect_to root_url
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include ApplicationHelper
    before_action :twitter
    def index
        @users = User.all
        @user = current_user
    end

    def show
        @profile = twitter.user(current_user.uid.to_i)
        @user = User.find(params[:id])
        # @tweets = twitter.user_timeline(@user.nickname)
        @test = current_user
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        user = User.find(params[:id])
        user.update(profile_params)
        redirect_to user_path(user)
    end

    private
        def twitter
            client = Twitter::REST::Client.new do |config|
                config.consumer_key = ENV['TWITTER_API_KEY']
                config.consumer_secret = ENV['TWITTER_API_SECRET']
                config.access_token = ENV['TWITTER_ACCSESS_TOKEN']
                config.access_token_secret = ENV['TWITTER_ACCSESS_TOKEN_SECRET']
            end
        end

        def profile_params
            params.require(:user).permit(:name, :description)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:uid] = user.uid
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  #! @current_userが未定義ならUser.find_by(uid: session[:uid])を代入
  def current_user
    if session[:uid]
      @current_user ||= User.find_by(uid: session[:uid])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    #! nil?は存在していればtrueを返す
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:uid)
    @current_user = nil
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="container">
    <div class="row">
        <div class="top-message col-md-offset-3 col-md-6">
            <% if flash[:message] %>
                <%= flash[:message] %>
            <% end %>
            <h1>Welcome to Bookers</h1>
            <% if logged_in? %>
                ログインしてる<br>
                ログイン名:<%= current_user.name %><br>
                ID:<%= current_user.nickname %><br>
                <%= image_tag current_user.image %>
            <% else %>
                ログインしてない
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <h1 class="nav navbar-nav navbar-left">Bookers4</h1>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to 'Home', user_path(current_user.id), class: "navia" %></li>
              <li><%= link_to 'Users', users_path, class: "navia" %></li>
              <li>
                <%= link_to logout_path, class:"navia" do %>
                 <i class="fab fa-twitter">ログアウト</i>
                <% end %>
              </li>
            <% else %>
              <li><%= link_to 'Home', root_path, class:"navia" %></li>
              <li><%= link_to 'About', '/about', class:"navia" %></li>
              <li>
                <%= link_to '/auth/twitter', class:"navia" do %>
                 <i class="fab fa-twitter">ログイン</i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_left.html.erb
<div class="col-xs-4">
    <h2>User info</h2>
    <%= image_tag user.image %>
    <table class="table">
        <tr>
            <th>User</th>
            <td><%= user.name %></td>
        </tr>
        <tr>
            <th>TwitterID</th>
            <td>@<%= user.nickname %></td>
        </tr>
        <tr>
            <th>Comment</th>
            <td><%= user.description %></td>
    </table>
    <%= link_to "Edit Profile", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Editing User</h1>
            <%= image_tag @user.image %>
            <%= form_for(@user) do |f| %>
                <div class="row">
                    <label for="name">Name</label>
                    <%= f.text_field :name, for:"name", class:"col-xs-12" %>
                </div>
                <div class="row">
                    <label for="prof">Profile</label>
                    <%= f.text_area :description, for:"prof", class:"col-xs-12" %>
                </div>
                <div class="actions row">
                    <%= f.submit "Update Profile", class:"btn btn-primary col-xs-12" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <%= render 'users/left', user: @user %>
        <div class="col-xs-8">
            <h2>User List</h2>
            <table class="table">
                <thead>
                    <th>ID</th>
                    <th>Image</th>
                    <th>User</th>
                    <th>TwitterID</th>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td><%= user.id %></td>
                        <td><%= link_to (image_tag user.image),user_path(user.id) %>
                        <td><%= user.name %></th>
                        <td>@<%= user.nickname %></th>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <%= render 'users/left', user: @user %>
        <div class="col-xs-8">
            <h2>Recent tweets</h2>
            <table class="table">
                <tr>
                    <%# <th>Time</th> %>
                    <%# <th>Tweet</th> %>
                <%# <% @tweets.each do |tweet| %> %>
                <tr>
                    <%# <td><%= tweet.created_at %></td> %>
                    <%# <td><%= tweet.text %></td> %>
                </tr>
               <%# <% end %> %>
            </table>
            <%= @profile %>
        </div>
    </div>
</div>